[package]
name = "qifi-rs"
version = "0.2.0"
authors = ["somewheve <somewheve@gmail.com>", "yutiansut <yutian@quantaxis.com.cn>"]
edition = "2018"
description = "A fast Api and Structure load"

[dependencies]
bson = "*"
serde_json = "*"
serde_derive = "1.0"
serde = { version = "1.0", features = ["derive"] } # 序列化
mongodb = "*"
serde_bytes = "0.10"

[profile.release]
lto = "fat"


[[example]]
name = "mongodbtest"

[[example]]
name = "single_test"